spring:
  application:
    name: analyzer-server
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true
      retry:
        use-random-policy: true
        max-interval: 6000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost
    instance-id: "${spring.application.name}:${server.port}"
    leaseRenewalIntervalInSeconds: 10

server:
  port: 9091

kafka.constants:
  url: "localhost:9092"
  action: "stats.user-actions.v1"
  similarity: "stats.events-similarity.v1"

management:
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"  # Открывает все endpoints (для production ограничьте)
      base-path: /actuator
  server:
    port: ${server.port}  # Использует основной порт приложения