DROP TABLE IF EXISTS request CASCADE;

CREATE TABLE IF NOT EXISTS request (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  event_id  BIGINT NOT NULL,
  requester_id BIGINT NOT NULL,
  status VARCHAR(15) NOT NULL,
  CONSTRAINT pk_request PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS ix_request_on_requester_id on request (requester_id);
CREATE INDEX IF NOT EXISTS ix_request_on_event_id on request (event_id);
CREATE INDEX IF NOT EXISTS ix_request_on_status on request (status);
