spring:
  application:
    name: gateway-server
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      fail-fast: true
      retry:
        initial-interval: 1000 # Начальный интервал (мс)
        max-interval: 2000     # Максимальный интервал (мс)
        multiplier: 1.5        # Множитель интервала
        max-attempts: 5        # Максимум попыток
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost
    instance-id: "${spring.application.name}:${server.port}"
    leaseRenewalIntervalInSeconds: 10
