spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: main_service_route
          uri: lb://main-service
          predicates:
            - Path=/**
        - id: event_service_route
          uri: lb://event_service
          predicates:
            - Path=/admin/compilations/**
            - Path=/compilations/**
            - Path=/users/{userId}/events/**
            - Path=/events/**
server:
  port: 8080